### ISSUE TITLE
Delete https://searx.blackspot.me

### ISSUE THREAD

**Issue by johnceltar** [dalf/searx-instances#35]
Instance added by the issue ??
unfortunetely all search engines are blocked (captcha) 
maybe there is in future a solution (i try referrer-spam by https://github.com/matomo-org/referrer-spam-blacklist 
see also https://www.kuketz-blog.de/searx-instanz-www-kuketz-suche-de-stellt-dienst-ein/
Sorry

**Comment by unixfox** [comment]
This instance was added in the issue #32.

Please note that removing your instance from the public list won't make you instantly unblocked from the search engine because your instance is now in the database of bots and removing it from searx.space will certainly not help.

You should try using filtron if you aren't using it in the first place. You may find bundled version of filtron with searx in this repository: https://github.com/searx/searx-docker

**Comment by dalf** [comment]
About filtron, there are also pre-compiled binaries: https://github.com/asciimoo/filtron/releases
