### ISSUE TITLE
Add https://searx.monicz.pl/

### ISSUE THREAD

**Issue by Zaczero** [dalf/searx-instances#82]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

**Comment by dalf** [comment]
It seems neither [filtron](https://github.com/asciimoo/filtron/) nor [antibot-proxy](https://github.com/unixfox/antibot-proxy) are installed.

In the current setup, different bots will abuse your instance until the google,etc.. ask for a captcha for each request.

**Comment by Zaczero** [comment]
@dalf I am fine with this, I want to have my instance as accessible as possible and using captcha system will be annoying to users. +it's not great for privacy +it can be bypassed with 10 mins of work. I don't think any of the systems you have mentioned will stop abuse completely so my strategy is just to monitor the situation, limit requests per second and possibly make some system to solve captchas presented by google.

**Comment by Zaczero** [comment]
I guess I can restrict my server to HTTP 2.0 / 3.0 only + TLS 1.3 minimum since not much software supports it (except for browser) which should result in less bot traffic. The question is will YOU be able to reach my instance?

**Comment by unixfox** [comment]
> @dalf I am fine with this, I want to have my instance as accessible as possible and using captcha system will be annoying to users.

It's not a CAPTCHA system, it doesn't affect the user experience from a normal Searx instance.

> +it's not great for privacy

It doesn't affect the privacy because the IP is associated with nothing personally identifiable.

> +it can be bypassed with 10 mins of work.

Every anti bot solution can be bypassed, the point of having one is to reduce the amount of bots not completely remove them.

> I don't think any of the systems you have mentioned will stop abuse completely so my strategy is just to monitor the situation, limit requests per second and possibly make some system to solve captchas presented by google.

I already tried this way in the past and limit the requests is what filtron already does and if you limit too much then you will ruin the user experience.
Solving the CAPTCHAs given by Google is also the way that I tried before and it just doesn't work. Google is able to recognize pretty quickly that it's a bot that is trying to solve the CAPTCHA and just give another one 5 minutes later.

> I guess I can restrict my server to HTTP 2.0 / 3.0 only + TLS 1.3 minimum since not much software supports it (except for browsers) which should result in less bot traffic. The question is will YOU be able to reach my instance?

Are you going to highly reduce the amount of possible users just for the sake of removing the bots? That's doesn't seem to follow your logic of an instance `as accessible as possible`.

Are you aware that most of the languages have libraries for HTTP2 & TLS 1.3 ?

**Comment by Zaczero** [comment]
_So what we have established so far:_
1. every protection system can by bypassed
2. there are libraries for HTTP2 & TLS 1.3

My take on this is that if someone knows how to use HTTP2 & TLS 1.3 libraries they must know how to change their user-agent to some legit-looking one. And from personal experience, significant most of the bot traffic comes from HTTP 1.1. Even though there are libraries for that unless it's target-specific attack you won't see it being used much. And if it's a target-specific attack we are back to point (1).

> Are you going to highly reduce the amount of possible users just for the sake of removing the bots? That's doesn't seem to follow your logic of an instance as accessible as possible.

What I meant by `as accessible as possible` was to people who can download and use the latest browser release. I don't care about artificial traffic _(since it's only a search engine)_ or outdated protocols.

---

My current server configuration is already dropping bad requests and limiting requests to 4r/s which is a reasonable amount. I just don't see a point of installing extra proxy just to drop some user agents. It's very very simple to bypass. If you want extra security from my side, as I said, I can restrict traffic to HTTP 2 & TLS 1.3 only.

---

PS.

> Solving the CAPTCHAs given by Google is also the way that I tried before and it just doesn't work. Google is able to recognize pretty quickly that it's a bot that is trying to solve the CAPTCHA and just give another one 5 minutes later.

Nothing stops me from running my checker 24/7 and solving reCAPTCHA costs like 2/3$ per 1000 so I think I'll manage this task.

**Comment by dalf** [comment]
searx.space should not have problem to connect to an HTTP/2 only server over TLS1.3.

Just tell me when you want the instance to be added.

**Comment by unixfox** [comment]
> _So what we have established so far:_
> 
>     1. every protection system can by bypassed
> 
>     2. there are libraries for HTTP2 & TLS 1.3
> 
> 
> My take on this is that if someone knows how to use HTTP2 & TLS 1.3 libraries they must know how to change their user-agent to some legit-looking one. And from personal experience, significant most of the bot traffic comes from HTTP 1.1. Even though there are libraries for that unless it's target-specific attack you won't see it being used much. And if it's a target-specific attack we are back to point (1).

Google starts blocking an instance if it thinks that a lot of requests looks like requests from a bot. By installing an anti bot solution you are highly reducing the chance of Google thinking that your server only do automated/bot requests and thus you can keep having the Google engine working on your Searx instance most of the time.

You said that it's not common to have a targeted attack and that most of the bots are just dumb so... why not giving filtron a try? It is efficient at filtering the dumb bots.

> > Are you going to highly reduce the amount of possible users just for the sake of removing the bots? That's doesn't seem to follow your logic of an instance as accessible as possible.
> 
> What I meant by `as accessible as possible` was to people who can download and use the latest browser release. I don't care about artificial traffic _(since it's only a search engine)_ or outdated protocols.

Unfortunately we aren't in an ideal world where everyone uses the latest browser version available. A huge chunk of the internet users is still using TLS 1.2 which is by no means outdated. It's a shame to disallow their ability to use your Searx instance.

I would also say that not everyone is using a TLS 1.3 and HTTP2 compatible browser due to:
- not having the administrator rights on the computer in order to upgrade the browser or switch to another compatible one (quite common in enterprise)
- not wanting to switch to a compatible browser because he is familiar with the current browser installed on the computer
- not having the money for upgrading to a new device. An example is someone that doesn't have enough disk space for a separate browser on his android phone and is forced to use the default integrated browser which only support TLS 1.2.

That's only some examples from a big list of others possible examples that one can't use a "modern" browser.

> > Solving the CAPTCHAs given by Google is also the way that I tried before and it just doesn't work. Google is able to recognize pretty quickly that it's a bot that is trying to solve the CAPTCHA and just give another one 5 minutes later.
> 
> Nothing stops me from running my checker 24/7 and solving reCAPTCHA costs like 2/3$ per 1000 so I think I'll manage this task.

Let's say that Google is giving you a CAPTCHA every 10 minutes, that's from 105$/year to 157$/year for solving the reCAPTCHA. That's quite the cost for running a Searx instance for free.

**Comment by Zaczero** [comment]
> 
> 
> searx.space should not have problem to connect to an HTTP/2 only server over TLS1.3.
> 
> Just tell me when you want to add the instance.

With my current configuration I've been only able to restrict minimum TLS 1.3 and minimum HTTP/1.1 From what I read it's for 'compatibility reasons' and even when HTTP/2 is used it's getting replaced internally with HTTP/1.1 I may switch to nginx at some point in the future which should allow me to do that the way I wanted. I guess that's fine for now... I will get a new server at the beginning of 2021. You may list my instance please.

---

@unixfox 

I think that my anti-bot solution with blocking TLS 1.2 and <HTTP/2 will work better than filtron's. I am not a big fan of limiting/blocking request by the headers as they are fully controlled by the client. It's a waste of CPU time for me.

There are quite a few public instances, if someone can't use mine then there are others available to chose from. I will just make sure that my instance is available with the latest Chromium/Firefox browsers.
